##########################################################
##################  所有dev的配置  #################
##########################################################

###################  服务名  ###################
server:
  name: accepter-ahjzsjj1

################# netty 监听端口 #########################
netty:
 # port: 9072  #外网9061
   port: 9563
################ zbus 消息队列 地址 ##########################
zbus:
  host: 192.168.1.64:15555
  yc-data-topic: topic-yc-data
  yc-ht-topic: topic-yc-ht
  yc-lx-topic: topic-yc-lx
  sjj-data-topic: topic-sjj-data
  sjj-ht-topic: topic-sjj-ht
  sjj-lx-topic: topic-sjj-lx
  sjj-img-topic: topic-sjj-img
  tj-data-topic: topic-tj-data
  tj-ht-topic: topic-tj-ht
  tj-lx-topic: topic-tj-lx
  tj-Training-topic: tj-Training-topic
  test-topic: topic-test
  dispatch-topic: topic-dispatch

###################  redis配置  ###################
spring:
  redis:
    host: 121.43.151.100
    port: 6379
    password: duanjudy@123
    timeout: 3000
    max-idle: 500
    min-idle: 50
    active: 2000
    wait: 1000
    cahce-names: xywg-sbgl-day-2,xywg-sbgl-min-30,xywg-sbgl-min-2,xywg-sbgl-hour-2

###################  ftp配置  ###################
ftp:
  host: 192.168.1.209
  port: 21
  username: smartsite
  password: 123456
  rootpath: device_platform
  filePath: d:/template/







