##########################################################
##################  所有dev的配置  #################
##########################################################

###################  项目启动端口  ###################
server:
  port: 9091


###################  xywg配置  ###################
xywg:
  swagger-open: true #是否开启swagger (true/false)
  auth-open: true
  sign-open: false #签名机制是否开启(true或false)
  #file-upload-path: d:/tmp  #文件上传目录(不配置的话为java.io.tmpdir目录)
  muti-datasource-open: false #是否开启多数据源(true/false)
  spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒
  netty-server-ports:  #服务端口 9060   , 分割
  netty-power-hex-ports:   #   电表 9011不配置不启动 16进制
  netty-water-hex-ports:   #   水表 9012 不配置不启动 16进制
  #netty-monitor-server-ports: 9072,9096,33900  #环境监控服务端口 如果后续设置多个请以逗号分隔
  netty-monitor-server-ports: 9099,9096,33900  #环境监控服务端口 如果后续设置多个请以逗号分隔
  netty-Heart-port: 8888  #心跳
  spray-manual-time: 5   #喷淋手动控制有效时间

  redisHead: device_platform
  upgrade-file-base-path: /upgrade/    #升级文件在本地的存储基础地址
  websocket:
    allowed-origins: http://localhost:8081,http://localhost:8080,http://192.168.1.186:8080,http://192.168.1.186:8081


##############################阿里配置#############################
ali:
  accessKeyId: LTAIM7w6KjwRXGxP
  accessKeySecret: 2Ixpjf7Dl3EGjvbqe3AziYIoFjL5mL
  iosAppKey: 25052872
  androidAppKey: 25054797
  env: DEV #DEV,PRODUCT
###################  spring配置  ###################


spring:
  redis:
    host: 121.43.151.100
    port: 6379
    password: duanjudy@123
    timeout: 3000
    max-idle: 500
    min-idle: 50
    active: 2000
    wait: 1000
    cahce-names: xywg-sbgl-day-2,xywg-sbgl-min-30,xywg-sbgl-min-2,xywg-sbgl-hour-2
    database: 7
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
      imagePath: /labor/
      imageLocalPath: http://192.168.1.124:8080/labor/
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
  devtools:
    restart:
      enabled: false #是否开启开发者工具（true/false）
      additional-paths: xywg-admin/src
      exclude: static/**,WEB-INF/view/**
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理
############ rabbitmq ########################
  rabbitmq:
      username: admin
      password: admin
      #virtualHost: XXX
      addresses: 192.168.1.199:5672
      publisher-confirms: true #发送确认
      publisher-returns: true   #返回错误确认
      listener:
        direct:
          acknowledge-mode: manual
        simple:
          acknowledge-mode: manual
##############数据库######################
  datasource:
    url: jdbc:mysql://192.168.20.160:8066/equipment_crane?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useServerPrepStmts=false&rewriteBatchedStatements=true&allowMultiQueries=true
    username: wyf
    password: wyf
    db-name: equipment_crane
    filters: log4j,mergeStat
#############日志##################
logging:
  level.root: info
  level.com.stylefeng: debug
  path: E;//logs//iot
  file: xywg.log

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:**/mapping/*.xml
  typeAliasesPackage: com.xywg.equipment.monitor.iot.modular.*.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  #  metaObjectHandler: com.xywg.equipmentmonitor.core.aop.MyMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

################ zbus 消息队列 地址 ##########################
zbus:
  host: 192.168.1.64:15555
  websocket-topic: topic-websocket
  helmet-topic: helmet-topic

job:
 open: false


ftp:
  host: 192.168.1.209
  port: 21
  username: smartsite
  password: 123456
  root-path: device_platform



