xywg:
 temperatureMin: 10
 temperatureMax: 60
 humidityMin:  0
 humidityMax:  100
 pm10: 600
 pm25: 600
 noise: 120
 windSpeed: 100
 nettyPort: 9800

###################  spring配置  ###################

spring:
  datasource:
    url: jdbc:mysql://118.31.69.25:3306/device_platform?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useServerPrepStmts=false&rewriteBatchedStatements=true&allowMultiQueries=true
    username: root
    password: Xingyun*_001
    db-name: device_platform
    filters: log4j,mergeStat
    #driver-class-name: com.mysql.jdbc.Driver
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理



###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/xingyun/equipment/simpleequipment/receive/modular/**/mapping/*.xml
  typeAliasesPackage: com.xywg.equipmentmonitor.modular.system.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 1
    logic-not-delete-value: 0
#    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
#    metaObjectHandler: com.xywg.equipmentmonitor.core.aop.MyMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用