
xywg:
  swagger-open: true #是否开启swagger (true/false)
  auth-open: true
  sign-open: false #签名机制是否开启(true或false)
  muti-datasource-open: false #是否开启多数据源(true/false)
  spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒
  netty-server-ports: 7777 #服务端口   , 分割
  netty-Heart-port: 8888  #心跳
  default-password: 123456 # 默认密码
  jwt:
    header: Authorization
    secret: defaultSecret
    expiration: 14400000
    authPath: xywg
    md5Key: randomKey


###################  spring配置  ###################

spring:
  datasource:
    url: jdbc:mysql://118.31.69.25:3306/device_platform?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useServerPrepStmts=false&rewriteBatchedStatements=true&allowMultiQueries=true
    username: root
    password: Xingyun*_001
    db-name: device_platform
    filters: log4j,mergeStat
  redis:
    host: 121.43.151.100
    port: 6379
    password: duanjudy@123
    timeout: 3000
    max-idle: 500
    min-idle: 50
    active: 2000
    wait: 1000
    cahce-names: xywg-sbgl-year-2,xywg-sbgl-day-2,xywg-sbgl-min-30,xywg-sbgl-min-2,xywg-sbgl-hour-2


###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:**/dao/mapping/*.xml
  #typeAliasesPackage: com.xingyun.equipment.**.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #metaObjectHandler: com.xywg.equipmentmonitor.core.aop.MyMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
server:
  port: 8081