server:
  port: 9096

xywg:
  crane-port: 9016  #监听端口,多个请以逗号分隔


spring:
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
      imagePath: /labor/
      #imageLocalPath: http://192.168.1.124:8080/labor/
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理
  datasource:
    url: jdbc:mysql://118.31.69.25:3306/device_platform?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useServerPrepStmts=false&rewriteBatchedStatements=true&allowMultiQueries=true
    username: root
    password: Xingyun*_001
    db-name: device_platform
    filters: log4j,mergeStat


logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: xywg.log

#---------------------------  mybatis-plus配置  -------------------------
mybatis-plus:
  mapper-locations: classpath*:**/mapping/*.xml
  typeAliasesPackage: com.xywg.iot.modules.*.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  #  metaObjectHandler: com.xywg.equipmentmonitor.core.aop.MyMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

zbus:
  host: 192.168.1.64:15555
  helmet-topic: helmet-topic

